### ISSUE TITLE
部分网站注入后不能加载

### ISSUE THREAD

**Issue by Skyline5723** [winner-hue/pjstealth#1]
网站是 https://www.hk01.com/
手动打开可以正常浏览

代码如下：
```python
from playwright.sync_api import sync_playwright
from pjstealth import stealth_sync

p = sync_playwright().start()
browser = p.chromium.launch(headless=False)

page = browser.new_page()
stealth_sync(page)

page.goto("https://www.hk01.com/")
time.sleep(10000)
``` 

一直转圈无法加载出来：
![image](https://github.com/winner-hue/pjstealth/assets/27749533/02385ceb-bc78-41b2-984c-76bd5155f3de)

**Comment by winner-hue** [comment]
将pjstealth更新的最新版本，按照如下写法：
import time

from playwright.sync_api import sync_playwright
from pjstealth import stealth_sync
from pjstealth import StealthConfig

proxy = {
    "server": "127.0.0.1:7890"
}
p = sync_playwright().start()
browser = p.chromium.launch(headless=False, proxy=proxy)

page = browser.new_page()
stealth_sync(page, StealthConfig(chrome_clientrectfeature=False))

page.goto("https://www.hk01.com/", timeout=100000000)
time.sleep(10000)

**Comment by Skyline5723** [comment]
可以了，谢谢大佬
